ogolne:
    type: htmlTag
    tag: h3
    content: Ustawienia aplikacji
    attributes:
        class: underline
appName:
    title: Nazwa aplikacji
    label: Nazwa aplikacji
    rules: Regex:/^[a-z0-9 \.\-\_]+$/i
    type: text
displayGravatar:
    type: fancyCheckbox
    label: Wyświetlać gravatary?
    baseValue: false
    value: 1
