settings:
  title: Ustawienia
  url: #
  icon: wrench
  order: 300
  collection:
    ogolne:
      title: Ogólne
      url: settings/general

    docnumbers:
      title: Numeracja dokumentów
      url: settings/numerator
      icon: terminal

    users:
      title: Użytkownicy
      url: administration/users
      icon: users

    roles:
      title: Role
      url: administration/roles
      permission: roles
      icon: lock